// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owacgosnuaqptrquqrrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YWNnb3NudWFxcHRycXVxcnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzgyMDgsImV4cCI6MjA2MTIxNDIwOH0.7rhBsBxxDo4vfRJ0w8MOmyuDITvVknGO5VzR5EB6bt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);